export const datas = [
    {
        id: 1,
        category: "coffee",
        items: [
            {
                id: "c1",
                name: "Americano",
                desc: "Espresso with added hot water",
                price: 2.79,
                imgUrl: "/images/coffee/1.jpg",
            },
            {
                id: "c2",
                name: "Macchiato",
                desc: "Espresso with a dash of milk",
                price: 3.29,
                imgUrl: "/images/coffee/2.jpg",
            },
            {
                id: "c3",
                name: "Mocha",
                desc: "Espresso with chocolate and steamed milk",
                price: 4.49,
                imgUrl: "/images/coffee/3.jpg",
            },
            {
                id: "c4",
                name: "Flat White",
                desc: "Espresso with velvety microfoam",
                price: 3.99,
                imgUrl: "/images/coffee/4.jpg",
            },
            {
                id: "c5",
                name: "Iced Coffee",
                desc: "Chilled coffee served over ice",
                price: 3.49,
                imgUrl: "/images/coffee/5.jpg",
            },
            {
                id: "c6",
                name: "Affogato",
                desc: "Espresso poured over vanilla ice cream",
                price: 4.99,
                imgUrl: "/images/coffee/6.jpg",
            },
            {
                id: "c7",
                name: "Irish Coffee",
                desc: "Coffee with Irish whiskey and cream",
                price: 5.99,
                imgUrl: "/images/coffee/7.jpg",
            },
            {
                id: "c8",
                name: "Turkish Coffee",
                desc: "Strong coffee with cardamom, boiled in a pot",
                price: 4.79,
                imgUrl: "/images/coffee/8.jpg",
            },
            {
                id: "c9",
                name: "Cuban Coffee",
                desc: "Sweetened espresso with demerara sugar",
                price: 4.29,
                imgUrl: "/images/coffee/9.jpg",
            },
            {
                id: "c10",
                name: "Caramel Macchiato",
                desc: "Espresso with vanilla and caramel, topped with milk foam",
                price: 4.49,
                imgUrl: "/images/coffee/10.jpg",
            },
            {
                id: "c11",
                name: "Hazelnut Latte",
                desc: "Espresso with steamed milk and hazelnut flavor",
                price: 4.29,
                imgUrl: "/images/coffee/1.jpg",
            },
            {
                id: "c12",
                name: "Ristretto",
                desc: "Short, strong shot of espresso",
                price: 2.99,
                imgUrl: "/images/coffee/2.jpg",
            },
            {
                id: "c13",
                name: "Vietnamese Egg Coffee",
                desc: "Sweetened coffee with egg yolk, condensed milk",
                price: 5.49,
                imgUrl: "/images/coffee/3.jpg",
            },
            {
                id: "c14",
                name: "Maple Pecan Latte",
                desc: "Espresso with steamed milk, maple syrup, and pecan flavor",
                price: 4.79,
                imgUrl: "/images/coffee/4.jpg",
            },
            {
                id: "c15",
                name: "Cardamom Coffee",
                desc: "Coffee brewed with cardamom spice",
                price: 3.79,
                imgUrl: "/images/coffee/5.jpg",
            },
            {
                id: "c16",
                name: "Coconut Coffee",
                desc: "Coffee with coconut milk and shredded coconut",
                price: 4.29,
                imgUrl: "/images/coffee/6.jpg",
            },
            {
                id: "c17",
                name: "Gingerbread Latte",
                desc: "Espresso with steamed milk, gingerbread flavor",
                price: 4.99,
                imgUrl: "/images/coffee/7.jpg",
            },
            {
                id: "c18",
                name: "Vanilla Bean Latte",
                desc: "Espresso with steamed milk and real vanilla beans",
                price: 4.49,
                imgUrl: "/images/coffee/8.jpg",
            },
            {
                id: "c19",
                name: "Cinnamon Dolce Latte",
                desc: "Espresso with steamed milk and cinnamon dolce syrup",
                price: 4.29,
                imgUrl: "/images/coffee/9.jpg",
            },
            {
                id: "c20",
                name: "Pumpkin Spice Latte",
                desc: "Espresso with steamed milk and pumpkin spice flavor",
                price: 4.79,
                imgUrl: "/images/coffee/10.jpg",
            },
            {
                id: "c21",
                name: "Espresso",
                desc: "Strong and concentrated coffee",
                price: 2.99,
                imgUrl: "/images/coffee/1.jpg",
            },
            {
                id: "c22",
                name: "Cappuccino",
                desc: "Espresso with steamed milk and foam",
                price: 3.49,
                imgUrl: "/images/coffee/2.jpg",
            },
        ],
    },
    {
        id: 2,
        category: "tea",
        items: [
            {
                id: "t1",
                name: "Earl Grey",
                desc: "Black tea flavored with bergamot oil",
                price: 2.99,
                imgUrl: "/images/tea/1.jpg",
            },
            {
                id: "t2",
                name: "Jasmine Green Tea",
                desc: "Green tea scented with jasmine blossoms",
                price: 3.49,
                imgUrl: "/images/tea/2.jpg",
            },
            {
                id: "t3",
                name: "Chamomile",
                desc: "Herbal tea known for its calming properties",
                price: 2.79,
                imgUrl: "/images/tea/3.jpg",
            },
            {
                id: "t4",
                name: "Peppermint Tea",
                desc: "Refreshing and minty herbal tea",
                price: 2.49,
                imgUrl: "/images/tea/4.jpg",
            },
            {
                id: "t5",
                name: "Hibiscus Berry Infusion",
                desc: "Fruity herbal tea with hibiscus and berries",
                price: 3.79,
                imgUrl: "/images/tea/5.jpg",
            },
            {
                id: "t6",
                name: "Oolong Tea",
                desc: "Partially oxidized tea with a unique flavor profile",
                price: 4.29,
                imgUrl: "/images/tea/6.jpg",
            },
            {
                id: "t7",
                name: "Detox Green Tea",
                desc: "Green tea blend with detoxifying herbs",
                price: 3.99,
                imgUrl: "/images/tea/7.jpg",
            },
            {
                id: "t8",
                name: "Rooibos Chai",
                desc: "Chai blend with caffeine-free rooibos tea",
                price: 4.49,
                imgUrl: "/images/tea/8.jpg",
            },
            {
                id: "t9",
                name: "Lemon Ginger Herbal Tea",
                desc: "Herbal tea with zesty lemon and ginger",
                price: 3.29,
                imgUrl: "/images/tea/9.jpg",
            },
            {
                id: "t10",
                name: "Matcha Latte",
                desc: "Green tea powder mixed with steamed milk",
                price: 4.99,
                imgUrl: "/images/tea/10.jpg",
            },
            {
                id: "t11",
                name: "Golden Turmeric Tea",
                desc: "Herbal tea with turmeric and spices",
                price: 4.79,
                imgUrl: "/images/tea/11.jpg",
            },
            {
                id: "t12",
                name: "White Tea with Peach",
                desc: "White tea blended with sweet peach flavor",
                price: 3.49,
                imgUrl: "/images/tea/1.jpg",
            },
            {
                id: "t13",
                name: "Blueberry Black Tea",
                desc: "Black tea infused with blueberry flavor",
                price: 3.99,
                imgUrl: "/images/tea/2.jpg",
            },
            {
                id: "t14",
                name: "Masala Chai",
                desc: "Traditional Indian spiced tea",
                price: 3.49,
                imgUrl: "/images/tea/3.jpg",
            },
            {
                id: "t15",
                name: "Mint Verbena Infusion",
                desc: "Herbal tea with mint and verbena leaves",
                price: 2.89,
                imgUrl: "/images/tea/4.jpg",
            },
            {
                id: "t16",
                name: "Green Tea",
                desc: "Light and refreshing green tea",
                price: 2.49,
                imgUrl: "/images/tea/5.jpg",
            },
            {
                id: "t17",
                name: "Chai Latte",
                desc: "Spiced tea with steamed milk",
                price: 3.99,
                imgUrl: "/images/tea/6.jpg",
            },
            // Add more tea items as needed
        ],
    },
    {
        id: 3,
        category: "snacks",
        items: [
            {
                id: "s1",
                name: "Caprese Salad Skewers",
                desc: "Tomato, mozzarella, and basil skewers drizzled with balsamic glaze",
                price: 5.49,
                imgUrl: "/images/snacks/1.jpg",
            },
            {
                id: "s2",
                name: "Vegetable Spring Rolls",
                desc: "Crispy spring rolls filled with fresh vegetables",
                price: 4.99,
                imgUrl: "/images/snacks/2.jpg",
            },
            {
                id: "s3",
                name: "Hummus Platter",
                desc: "Creamy hummus served with pita bread and veggies",
                price: 6.29,
                imgUrl: "/images/snacks/3.jpg",
            },
            {
                id: "s4",
                name: "Spinach and Artichoke Dip",
                desc: "Warm dip with spinach, artichokes, and melted cheese",
                price: 7.99,
                imgUrl: "/images/snacks/4.jpg",
            },
            {
                id: "s5",
                name: "Buffalo Cauliflower Bites",
                desc: "Crispy cauliflower bites tossed in buffalo sauce",
                price: 5.79,
                imgUrl: "/images/snacks/5.jpg",
            },
            {
                id: "s6",
                name: "Avocado Toast",
                desc: "Sliced avocado on toasted artisan bread with seasoning",
                price: 6.49,
                imgUrl: "/images/snacks/6.jpg",
            },
            {
                id: "s7",
                name: "Mozzarella Sticks",
                desc: "Golden-brown mozzarella sticks with marinara sauce",
                price: 4.29,
                imgUrl: "/images/snacks/7.jpg",
            },
            {
                id: "s8",
                name: "Stuffed Jalapeños",
                desc: "Jalapeños filled with cream cheese and wrapped in bacon",
                price: 5.99,
                imgUrl: "/images/snacks/8.jpg",
            },
            {
                id: "s9",
                name: "Bruschetta",
                desc: "Toasted bread topped with diced tomatoes, basil, and garlic",
                price: 4.79,
                imgUrl: "/images/snacks/9.jpg",
            },
            {
                id: "s10",
                name: "Truffle Fries",
                desc: "Crispy fries tossed in truffle oil and Parmesan cheese",
                price: 3.99,
                imgUrl: "/images/snacks/10.jpg",
            },
            {
                id: "s11",
                name: "Greek Yogurt Parfait",
                desc: "Layered parfait with Greek yogurt, honey, and granola",
                price: 5.49,
                imgUrl: "/images/snacks/1.jpg",
            },
            {
                id: "s12",
                name: "Sweet Potato Chips",
                desc: "Thinly sliced sweet potatoes, baked to perfection",
                price: 4.29,
                imgUrl: "/images/snacks/2.jpg",
            },
            {
                id: "s13",
                name: "Cheese and Charcuterie Board",
                desc: "Assortment of cheeses, meats, and accompaniments",
                price: 8.99,
                imgUrl: "/images/snacks/3.jpg",
            },
            {
                id: "s14",
                name: "Spicy Edamame",
                desc: "Edamame beans tossed in a spicy seasoning",
                price: 3.49,
                imgUrl: "/images/snacks/4.jpg",
            },
            {
                id: "s15",
                name: "Cucumber Rolls",
                desc: "Cucumber slices rolled with cream cheese and herbs",
                price: 4.79,
                imgUrl: "/images/snacks/5.jpg",
            },
            {
                id: "s16",
                name: "Garlic Parmesan Knots",
                desc: "Soft knots of bread brushed with garlic butter and Parmesan",
                price: 5.29,
                imgUrl: "/images/snacks/6.jpg",
            },
            {
                id: "s17",
                name: "Smoked Salmon Crostini",
                desc: "Crostini topped with smoked salmon and herbed cream cheese",
                price: 7.49,
                imgUrl: "/images/snacks/7.jpg",
            },
            {
                id: "s18",
                name: "Cajun Popcorn Shrimp",
                desc: "Crispy popcorn shrimp with Cajun seasoning",
                price: 6.79,
                imgUrl: "/images/snacks/8.jpg",
            },
            {
                id: "s19",
                name: "Quinoa Salad Cups",
                desc: "Mini cups filled with quinoa salad and veggies",
                price: 5.99,
                imgUrl: "/images/snacks/9.jpg",
            },
            {
                id: "s20",
                name: "Baked Brie with Jam",
                desc: "Brie cheese baked until gooey, served with fruit jam",
                price: 8.29,
                imgUrl: "/images/snacks/10.jpg",
            },
            {
                id: "s21",
                name: "Croissant",
                desc: "Flaky and buttery pastry",
                price: 1.99,
                imgUrl: "/images/snacks/1.jpg",
            },
            {
                id: "s22",
                name: "Fruit Parfait",
                desc: "Yogurt with fresh fruits and granola",
                price: 4.49,
                imgUrl: "/images/snacks/2.jpg",
            },
            // Add more snacks items as needed
        ],
    },
    {
        id: 3,
        category: "desserts",
        items: [
            {
                id: "d1",
                name: "Tiramisu",
                desc: "Classic Italian dessert with layers of coffee-soaked ladyfingers and mascarpone cream",
                price: 6.99,
                imgUrl: "/images/desserts/1.jpg",
            },
            {
                id: "d2",
                name: "Red Velvet Cake",
                desc: "Moist red velvet cake with cream cheese frosting",
                price: 5.49,
                imgUrl: "/images/desserts/2.jpg",
            },
            {
                id: "d3",
                name: "Chocolate Soufflé",
                desc: "Warm and gooey chocolate soufflé with a molten center",
                price: 7.29,
                imgUrl: "/images/desserts/3.jpg",
            },
            {
                id: "d4",
                name: "Key Lime Pie",
                desc: "Tangy key lime filling in a buttery graham cracker crust",
                price: 4.99,
                imgUrl: "/images/desserts/4.jpg",
            },
            {
                id: "d5",
                name: "Panna Cotta",
                desc: "Creamy Italian dessert topped with fruit compote",
                price: 6.49,
                imgUrl: "/images/desserts/5.jpg",
            },
            {
                id: "d6",
                name: "Cannoli",
                desc: "Crispy pastry shells filled with sweet ricotta cream",
                price: 5.79,
                imgUrl: "/images/desserts/6.jpg",
            },
            {
                id: "d7",
                name: "Strawberry Shortcake",
                desc: "Layers of sponge cake, fresh strawberries, and whipped cream",
                price: 5.99,
                imgUrl: "/images/desserts/7.jpg",
            },
            {
                id: "d8",
                name: "Banana Bread Pudding",
                desc: "Warm bread pudding with banana slices and caramel sauce",
                price: 6.79,
                imgUrl: "/images/desserts/8.jpg",
            },
            {
                id: "d9",
                name: "Lemon Bars",
                desc: "Zesty lemon bars with a buttery shortbread crust",
                price: 4.29,
                imgUrl: "/images/desserts/9.jpg",
            },
            {
                id: "d10",
                name: "Apple Crisp",
                desc: "Baked apple slices with a crumbly oat topping",
                price: 5.49,
                imgUrl: "/images/desserts/10.jpg",
            },
            {
                id: "d11",
                name: "Chocolate Covered Strawberries",
                desc: "Fresh strawberries dipped in rich chocolate",
                price: 3.99,
                imgUrl: "/images/desserts/1.jpg",
            },
            {
                id: "d12",
                name: "Raspberry Cheesecake",
                desc: "Creamy cheesecake with a raspberry swirl",
                price: 7.49,
                imgUrl: "/images/desserts/2.jpg",
            },
            {
                id: "d13",
                name: "Pecan Pie",
                desc: "Classic pecan pie with a buttery crust",
                price: 6.29,
                imgUrl: "/images/desserts/3.jpg",
            },
            {
                id: "d14",
                name: "Creme Brulee",
                desc: "Vanilla custard with a caramelized sugar crust",
                price: 6.99,
                imgUrl: "/images/desserts/4.jpg",
            },
            {
                id: "d15",
                name: "Blueberry Cheesecake Bars",
                desc: "Cheesecake bars with a blueberry swirl",
                price: 5.79,
                imgUrl: "/images/desserts/5.jpg",
            },
            {
                id: "d16",
                name: "Chocolate Mousse",
                desc: "Silky chocolate mousse topped with whipped cream",
                price: 6.49,
                imgUrl: "/images/desserts/6.jpg",
            },
            {
                id: "d17",
                name: "Pistachio Baklava",
                desc: "Layers of phyllo dough filled with pistachios and honey",
                price: 7.79,
                imgUrl: "/images/desserts/7.jpg",
            },
            {
                id: "d18",
                name: "Coconut Cream Pie",
                desc: "Coconut-infused custard in a flaky pie crust",
                price: 5.29,
                imgUrl: "/images/desserts/8.jpg",
            },
            {
                id: "d19",
                name: "Mango Sorbet",
                desc: "Refreshing mango sorbet served in a fruit shell",
                price: 4.49,
                imgUrl: "/images/desserts/9.jpg",
            },
            {
                id: "d20",
                name: "Rum Raisin Bread Pudding",
                desc: "Bread pudding with rum-soaked raisins and a caramel drizzle",
                price: 7.99,
                imgUrl: "/images/desserts/10.jpg",
            },
            {
                id: "d21",
                name: "Chocolate Cake",
                desc: "Rich and decadent chocolate cake",
                price: 5.99,
                imgUrl: "/images/desserts/1.jpg",
            },
            {
                id: "d22",
                name: "Cheesecake",
                desc: "Creamy and smooth cheesecake",
                price: 4.99,
                imgUrl: "/images/desserts/2.jpg",
            },
            // Add more desserts items as needed
        ],
    }
];